[package]
name = "dpp-python"
version = "0.1.4"
edition = "2024"
license = "MIT"
description = "Python bindings for the dpp Apple disk image and package toolkit"

[lib]
name = "dpp"
crate-type = ["cdylib"]

[dependencies]
dpp = { version = "0.3.4", path = "../dpp" }
pyo3 = { version = "0.28.1", features = ["extension-module"] }
